### ISSUE TITLE
tracetree doesn't build with GHC 8.4.1

### ISSUE THREAD

**Issue by grayjay** [edsko/tracetree#3]
It looks like tracetree has a restrictive upper bound on bifunctors, and the older version of bifunctors (5.4.2) requires template-haskell < 2.13.  When I tried building with `--allow-newer=tracetree:bifunctors`, I got a compile error:

```
$ cabal new-build --allow-newer=tracetree:bifunctors 
Resolving dependencies...
Build profile: -w ghc-8.4.1 -O1
In order, the following will be built (use -v for more details):
 - tracetree-0.1.0.1 (lib) (first run)
Configuring library for tracetree-0.1.0.1..
Preprocessing library for tracetree-0.1.0.1..
Building library for tracetree-0.1.0.1..
[1 of 6] Compiling Debug.Trace.Tree.Assoc ( src/Debug/Trace/Tree/Assoc.hs, /home/kristen/projects/tracetree-0.1.0.1/dist-newstyle/build/x86_64-linux/ghc-8.4.1/tracetree-0.1.0.1/build/Debug/Trace/Tree/Assoc.o )

src/Debug/Trace/Tree/Assoc.hs:41:10: error:
    • No instance for (Semigroup (Assoc k v))
        arising from the superclasses of an instance declaration
    • In the instance declaration for ‘Monoid (Assoc k v)’
   |
41 | instance Monoid (Assoc k v) where
   |          ^^^^^^^^^^^^^^^^^^
```

**Comment by edsko** [comment]
Will take a look.

**Comment by edsko** [comment]
Fixed this for the library, but I can't check the executable yet because some of the dependencies don't build with 8.4.1 either (right now it gets stuck one `OneTuple` with a similar error as above). Closing this; feel free to open another ticket if/when dependencies do build and `ttrender` is at fault :) (I don't have the time to track down all those dependencies at the moment.)

Thanks for the report!

**Comment by grayjay** [comment]
Thanks for making the release!  I mainly wanted to update the cabal CI job, which only builds the tracetree library.
